---
- hosts: localhost
  become: true

  tasks:
    - name: Install Neovim
      apt:
        name: neovim
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Curl
      apt:
        name: curl
        state: present

    - name: Create Neovim directory
      file:
        path: "~/.config/nvim/"
        state: directory
    
    - name: Descargar archivo plug.vim de vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.local/share/nvim/site/autoload/plug.vim
        mode: 0644

    - name: Clone Neovim configuration repository
      git:
        repo: https://github.com/user/neovim-config.git
        dest: "~/.config/nvim/"
