---
- hosts: localhost
  become: true

  tasks:
    - name: Install Neovim
      apt:
        name: neovim
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Curl
      apt:
        name: curl
        state: present

    - name: Create Neovim directory
      file:
        path: "~/.config/nvim/"
        state: directory
    
    - name: Instalar vim-plug
      become: yes
      shell: |
        curl -fLo "{{ lookup('env', 'XDG_DATA_HOME') or '~/.local/share' }}/nvim/site/autoload/plug.vim" --create-dirs \
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: Clone Neovim configuration repository
      git:
        repo: https://github.com/user/neovim-config.git
        dest: "~/.config/nvim/"
