---
- hosts: localhost
  become: true

  tasks:
    - name: Install Neovim
      apt:
        name: neovim
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Curl
      apt:
        name: curl
        state: present

    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Create Neovim directory
      file:
        path: "~/.config/nvim/"
        state: directory

    - name: Copiar My init.vim
      copy:
        src: ./init.vim
        dest: ~/.config/nvim/
    
    - name: Descargar Vim-Plug
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ lookup('env', 'XDG_DATA_HOME') or '~/.local/share' }}/nvim/site/autoload/plug.vim"
        mode: '0644'



