---
- hosts: localhost
  become: true

  tasks:
    - name: Install Neovim
      ansible.builtin.package:
        name: neovim
        state: present

    - name: Install Git
      ansible.builtin.package:
        name: git
        state: present

    - name: Install curl package
      ansible.builtin.package:
        name: curl
        state: present

    - name: Install Node.js
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Instalar dependencias necesarias
      ansible.builtin.package:
        name:
          [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "gnupg",
            "software-properties-common",
          ]
        state: present

    - name: Agregar clave de WineHQ
      ansible.builtin.apt_key:
        url: https://dl.winehq.org/wine-builds/winehq.key
        state: present

    - name: Instalar Wine
      ansible.builtin.package:
        name: ["winehq-devel"]
        state: present
