---
- hosts: localhost
  become: true

  tasks:
    - name: Install Neovim
      ansible.builtin.package:
        name: neovim
        state: present

    - name: Install Git
      ansible.builtin.package:
        name: git
        state: present

    - name: Install curl package
      ansible.builtin.package:
       name: curl
       state: present

    - name: Install Node.js 
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Create Neovim directory
      ansible.builtin.file:
        path: ~/.config/nvim/
        state: directory

    - name: Copiar My_init.vim
      ansible.builtin.copy:
        src: ./init.vim
        dest: ~/.config/nvim/
    
    - name: Create Vim-Plug directory
      ansible.builtin.file:
        path: /root/.local/share/nvim/site/autoload
        state: directory

    - name: Descargar Vim-Plug
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ lookup('env', 'XDG_DATA_HOME') or '~/.local/share' }}/nvim/site/autoload/plug.vim"
        mode: '0644'



