version: '3'

tasks: 
  playbook:
    desc: Install ansible-playbook
    cmds:
      - apt-get update -y
      - apt-get install ansible 
  
  install:
    desc: install my personal settings
    cmds:
      - ansible-playbook miconfig.yml